name: "기능 추가"
description: 기능 추가 Issue 작성 양식입니다.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "AI 챗봇 스트리밍 기능 추가"
  - type: dropdown
    attributes:
      label: 알림 대상자
      description: 알림을 받을 대상자를 선택해주세요.
      multiple: true
      options:
        - \@qaws5656
        - \@oereo
      default: 0
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 작업 설명
      description: 어떠한 기능을 추가하시는 건지 적어주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: how-to-implement
    attributes:
      label: 접근 방법
      description: 고려하신 방법이나, 접근에 대해서 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: 대체 방안 (선택 사항)
      description: 상기한 방법 외에 다른 대안이 있다면 적어주세요.
      render: shell
      placeholder: 설명을 적어주세요.
    validations:
      required: false